worlds:
  world: tutorial
  remove: beggar
  add: peasant
tp:
  tp1:
    x: -4
    y: 80
    z: 188
    destination:
      world: world
      x: -6
      y: 61
      z: -1
  tp2:
    x: -4
    y: 80
    z: 188
    destination:
      world: world
      x: 5
      y: 81
      z: 188
  tp3:
    x: 21
    y: 70
    z: -134
    destination:
      world: world
      x: 36
      y: 71
      z: -133
  tuttp1:
    x: 141
    y: 67
    z: -253
    destination:
      world: world
      x: 100
      y: 100
      z: 100
  tp:
    x: 99
    y: 40
    z: 99
    destination:
      world: world
      x: 100
      y: 100
      z: 100
